---
- name: Add asdf nodejs plugin if not already added
  become: yes
  shell: >
    source $HOME/.asdf/asdf.sh &&
    asdf plugin-list | grep -q "^nodejs$" || asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Install Node.js using asdf
  become: yes
  shell: >
    source $HOME/.asdf/asdf.sh &&
    asdf install nodejs latest &&
    asdf global nodejs latest
  args:
    executable: /bin/bash

- name: Install npm
  become: yes
  shell: >
    source $HOME/.asdf/asdf.sh &&
    npm install -g npm
  args:
    executable: /bin/bash
